"""Read/write layer for review verdicts and the state you own.

Two things live here that must not be confused with each other:

  job_reviews   what the model decided — regenerable, thrown away and rebuilt
                whenever the prompt, model, or preferences change
  job_state     what you decided — read, favorited; written once and never
                regenerated by anything

They are separate tables so a re-review can rewrite every verdict without
touching which jobs you have already read.
"""

from __future__ import annotations

import json
import sqlite3
from typing import Any, Iterable

from .dedup import collapse, twins
from .store import utcnow

VIEWS = ("unread", "favorite", "read")

# Reviews are per content version, so a posting becomes eligible again when a
# backfill fills in its description or a board re-lists it with changes.
PENDING_SQL = """
    SELECT r.id AS raw_job_id, r.board, r.board_job_id, r.title, r.company,
           r.location, r.date_posted, r.job_url, r.payload
    FROM raw_jobs r
    JOIN (SELECT board, board_job_id, MAX(id) AS newest
          FROM raw_jobs GROUP BY board, board_job_id) latest
      ON latest.newest = r.id
    WHERE NOT EXISTS (SELECT 1 FROM job_reviews v WHERE v.raw_job_id = r.id)
    ORDER BY r.id
"""

# The list the web views are built from. Three joins earn their place:
#   latest_review  one verdict per posting, the newest
#   latest_raw     the freshest board data for that posting
#   first_seen     the EARLIEST sighting, not the latest — see order_by note
LIST_SQL = """
    WITH latest_review AS (
        SELECT v.* FROM job_reviews v
        JOIN (SELECT board, board_job_id, MAX(id) AS mid
              FROM job_reviews GROUP BY board, board_job_id) m ON m.mid = v.id
    ), latest_raw AS (
        SELECT r.* FROM raw_jobs r
        JOIN (SELECT board, board_job_id, MAX(id) AS n
              FROM raw_jobs GROUP BY board, board_job_id) x ON x.n = r.id
    ), first_seen AS (
        SELECT board, board_job_id, MIN(seen_at) AS first_seen_at
        FROM job_sightings GROUP BY board, board_job_id
    )
    SELECT v.board, v.board_job_id, v.tags, v.summary, v.stage,
           r.title, r.company, r.location, r.date_posted, r.job_url,
           f.first_seen_at,
           COALESCE(s.is_read, 0) AS is_read,
           COALESCE(s.is_favorite, 0) AS is_favorite
    FROM latest_review v
    JOIN latest_raw r  ON r.board = v.board AND r.board_job_id = v.board_job_id
    JOIN first_seen f  ON f.board = v.board AND f.board_job_id = v.board_job_id
    LEFT JOIN job_state s ON s.board = v.board AND s.board_job_id = v.board_job_id
    WHERE v.verdict = 'keep' {where}
    -- Sorted by the posting's FIRST sighting. Using the latest would send every
    -- job still live on the boards back to the top of `unread` every day, and
    -- the ordering would never settle.
    ORDER BY f.first_seen_at DESC, r.date_posted DESC, r.id DESC
"""

VIEW_FILTERS = {
    "unread": "AND COALESCE(s.is_read, 0) = 0",
    "read": "AND COALESCE(s.is_read, 0) = 1",
    "favorite": "AND COALESCE(s.is_favorite, 0) = 1",
}


class ReviewStore:
    def __init__(self, conn: sqlite3.Connection):
        self.conn = conn

    # --- runs -------------------------------------------------------------

    def start_run(self, model: str, prefs_hash: str) -> int:
        cur = self.conn.execute(
            "INSERT INTO review_runs (started_at, model, prefs_hash) VALUES (?, ?, ?)",
            (utcnow(), model, prefs_hash),
        )
        self.conn.commit()
        return cur.lastrowid

    def finish_run(self, run_id: int, status: str, **counts: int) -> None:
        fields = ", ".join(f"{k} = ?" for k in counts)
        self.conn.execute(
            f"UPDATE review_runs SET finished_at = ?, status = ?{', ' + fields if fields else ''}"
            " WHERE id = ?",
            (utcnow(), status, *counts.values(), run_id),
        )
        self.conn.commit()

    def recent_runs(self, limit: int = 10) -> list[sqlite3.Row]:
        return self.conn.execute(
            "SELECT * FROM review_runs ORDER BY id DESC LIMIT ?", (limit,)
        ).fetchall()

    # --- reviews ----------------------------------------------------------

    def pending(self, limit: int | None = None) -> list[sqlite3.Row]:
        sql = PENDING_SQL + (" LIMIT ?" if limit is not None else "")
        return self.conn.execute(sql, (limit,) if limit is not None else ()).fetchall()

    def clear_reviews(self) -> int:
        """Drop every verdict so the next pass re-reviews everything.

        Leaves job_state untouched — that is the whole point of the split.
        """
        n = self.conn.execute("DELETE FROM job_reviews").rowcount
        self.conn.execute("DELETE FROM review_runs")
        self.conn.commit()
        return n

    def record(
        self,
        run_id: int,
        job: sqlite3.Row,
        stage: str,
        verdict: str,
        drop_reason: str | None = None,
        languages: Iterable[str] = (),
        tags: Iterable[str] = (),
        summary: str | None = None,
        model: str | None = None,
        error: str | None = None,
    ) -> None:
        self.conn.execute(
            """INSERT OR REPLACE INTO job_reviews
               (run_id, board, board_job_id, raw_job_id, stage, verdict, drop_reason,
                languages, tags, summary, model, error, reviewed_at)
               VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
            (
                run_id, job["board"], job["board_job_id"], job["raw_job_id"],
                stage, verdict, drop_reason,
                json.dumps(list(languages)), json.dumps(list(tags)),
                summary, model, error, utcnow(),
            ),
        )

    def drop_reasons(self) -> list[sqlite3.Row]:
        return self.conn.execute(
            """SELECT COALESCE(v.drop_reason, '(none)') AS reason, COUNT(*) AS n
               FROM job_reviews v
               JOIN (SELECT board, board_job_id, MAX(id) AS mid
                     FROM job_reviews GROUP BY board, board_job_id) m ON m.mid = v.id
               WHERE v.verdict = 'drop'
               GROUP BY reason ORDER BY n DESC"""
        ).fetchall()

    # --- the views --------------------------------------------------------

    def list_jobs(self, view: str = "unread", fold_duplicates: bool = True) -> list[dict[str, Any]]:
        if view not in VIEW_FILTERS:
            raise ValueError(f"unknown view {view!r}; expected one of {', '.join(VIEWS)}")
        rows = self.conn.execute(LIST_SQL.format(where=VIEW_FILTERS[view])).fetchall()
        jobs = [{**dict(r), "tags": json.loads(r["tags"] or "[]")} for r in rows]
        if not fold_duplicates:
            return jobs
        # Folding happens after filtering, which is safe because read and
        # favorite are applied to every copy of a posting — the copies never
        # disagree, so they never straddle two views.
        folded = collapse(jobs)
        folded.sort(key=lambda j: (j["first_seen_at"] or "", j["date_posted"] or ""), reverse=True)
        return folded

    def counts(self) -> dict[str, int]:
        return {view: len(self.list_jobs(view)) for view in VIEWS}

    # --- state you own ----------------------------------------------------

    def _touch(self, board: str, board_job_id: str) -> None:
        self.conn.execute(
            "INSERT OR IGNORE INTO job_state (board, board_job_id) VALUES (?, ?)",
            (board, board_job_id),
        )

    def mark_read(self, board: str, board_job_id: str, read: bool = True) -> None:
        """Applies to every copy of the posting, not just the one clicked.

        Without this, marking the LinkedIn copy read leaves the Indeed copy in
        `unread` forever — the exact failure that made dedup worth building.
        """
        stamp = utcnow() if read else None
        for b, jid in twins(self.conn, board, board_job_id):
            self._touch(b, jid)
            self.conn.execute(
                "UPDATE job_state SET is_read = ?, read_at = ? WHERE board = ? AND board_job_id = ?",
                (1 if read else 0, stamp, b, jid),
            )
        self.conn.commit()

    def toggle_favorite(self, board: str, board_job_id: str) -> bool:
        self._touch(board, board_job_id)
        row = self.conn.execute(
            "SELECT is_favorite FROM job_state WHERE board = ? AND board_job_id = ?",
            (board, board_job_id),
        ).fetchone()
        new = 0 if row["is_favorite"] else 1
        stamp = utcnow() if new else None
        for b, jid in twins(self.conn, board, board_job_id):
            self._touch(b, jid)
            self.conn.execute(
                "UPDATE job_state SET is_favorite = ?, favorited_at = ?"
                " WHERE board = ? AND board_job_id = ?",
                (new, stamp, b, jid),
            )
        self.conn.commit()
        return bool(new)
